---
- name: put postgresql db creation script
  template:
    src: "files/createdb.sql"
    dest: /var/lib/postgresql

- name: put postgresql role creation script
  template:
    src: "files/createuser.sql"
    dest: /var/lib/postgresql

- name: Initialize postgres Database and user
  become_user: postgres
  command: "psql -f ~/createuser.sql"

- name: Initialize postgres Database and user
  become_user: postgres
  command: "psql -f ~/createdb.sql"